"""
Guardrail Agent
---------------
The last gate before output reaches the user.

Responsibilities:
  1. Enforce SEBI disclaimer (mandatory per Track 9 problem statement)
  2. Detect and refuse unlicensed financial advice patterns
  3. Flag any output that gives a specific BUY/SELL recommendation on a named stock
  4. Ensure all tax figures include appropriate disclaimers
  5. Add RBI/SEBI regulatory references where relevant
  6. Log guardrail decisions in audit trail

This agent never blocks output — it adds/modifies disclaimers and flags.
"""

SEBI_DISCLAIMER = (
    "IMPORTANT: This output is generated by an AI model and is for informational and educational "
    "purposes only. It does not constitute licensed financial advice as defined under the "
    "SEBI (Investment Advisers) Regulations, 2013. Past returns are not indicative of future performance. "
    "Please consult a SEBI-registered Investment Adviser before making any investment decisions."
)

RBI_DISCLAIMER = (
    "Tax computations are based on publicly available Indian tax laws. "
    "Consult a qualified Chartered Accountant for accurate tax filing."
)

BLOCKED_PATTERNS = [
    "buy ", "sell ", "invest in ", "purchase ", "avoid ",
    "guaranteed return", "assured return", "risk-free",
]

STOCK_SIGNALS = ["nse:", "bse:", "₹ target", "price target"]


class GuardrailAgent:
    def run(self, advice: dict) -> dict:
        guardrail_log = []

        # ── Rule 1: Inject SEBI disclaimer ───────────────────────────────────
        advice["sebi_disclaimer"] = SEBI_DISCLAIMER
        guardrail_log.append({"rule": "sebi_disclaimer", "action": "injected"})

        # ── Rule 2: Inject RBI/tax disclaimer ────────────────────────────────
        advice["tax_disclaimer"] = RBI_DISCLAIMER
        guardrail_log.append({"rule": "rbi_tax_disclaimer", "action": "injected"})

        # ── Rule 3: Scan priorities for blocked patterns ──────────────────────
        priorities = advice.get("priorities", [])
        flagged = []
        for i, p in enumerate(priorities):
            action_text = (p.get("action", "") + " " + p.get("dimension", "")).lower()
            for pattern in BLOCKED_PATTERNS:
                if pattern in action_text and "don't" not in action_text:
                    flagged.append({
                        "priority_index": i,
                        "pattern": pattern,
                        "note": "Potential unlicensed advice language detected — verify context."
                    })

        if flagged:
            advice["guardrail_flags"] = flagged
            guardrail_log.append({
                "rule": "advice_language_check",
                "action": "flags_added",
                "count": len(flagged)
            })
        else:
            guardrail_log.append({
                "rule": "advice_language_check",
                "action": "passed",
            })

        # ── Rule 4: Add "not a specific stock recommendation" note ────────────
        advice["investment_note"] = (
            "All fund/instrument suggestions are categories, not specific scheme recommendations. "
            "Choose direct-plan, low-expense-ratio funds from SEBI-registered AMCs."
        )
        guardrail_log.append({"rule": "no_specific_scheme", "action": "note_added"})

        # ── Rule 5: Add escalation path ──────────────────────────────────────
        advice["escalation"] = {
            "when_to_seek_human_advisor": [
                "Portfolio size above ₹50 lakhs",
                "Complex tax situations (foreign income, ESOPs, multiple employers)",
                "Business income or presumptive taxation",
                "Estate or succession planning",
                "Significant life events with large amounts (above ₹25L)",
            ],
            "find_sebi_advisor": "https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=13",
        }
        guardrail_log.append({"rule": "escalation_path", "action": "added"})

        advice["guardrail_audit"] = guardrail_log
        return advice
